name: resolve

on:
  push:
    branches:
      - "master"
    tags:
      - "!*"
  pull_request:
    branches:
    - "*"

jobs:
  resolve:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v3
    - uses: SwiftyLab/setup-swift@latest
      with:
        swift-version: "6.0"
    - name: Build Package
      run: swift package resolve